const STATUS_CODE_OK = 200; // GET, PUT SUCESSFULL
const STATUS_CODE_CREATED = 201; // POST SUCESSFULL
const STATUS_CODE_BAD_REQUEST = 400; // BAD REQUEST
const STATUS_CODE_NOT_FOUND = 404; // NO DATA 

module.exports = {
    STATUS_CODE_OK,
    STATUS_CODE_CREATED,
    STATUS_CODE_BAD_REQUEST,
    STATUS_CODE_NOT_FOUND
}